### ISSUE TITLE
Create Student Model

### ISSUE THREAD

**Issue by JosephCW** [JosephCW/mvc-app#5]
- [x] creating the model (and properties),
- [x] creating sample data that fits the model,
- [x] seeding your sample data
- [x] routing requests to your controller
- [x] implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)
- [ ] implementing implementing the five views used to listall/create/read/update/delete (CRUD).
- [ ] update the application navigation to provide access to your resource
- [ ] update the application navigation to provide access to your developer page.

**Comment by cweltonsmith** [comment]
Created Student model
